Ignore unset-but-used-variable
Thanks to

/home/ten-young/bu2016/S2016/cs440/cs540p2_guh_ten-young/test.cpp: In function ‘void access_by_key()’:
/home/ten-young/bu2016/S2016/cs440/cs540p2_guh_ten-young/test.cpp:47:10: error: variable ‘thrown’ set but not used [-Werror=unused-but-set-variable]
     bool thrown = false;
          ^
/home/ten-young/bu2016/S2016/cs440/cs540p2_guh_ten-young/test-kec.cpp: In instantiation of ‘void run_test(int) [with MAP_T = test_map]’:
/home/ten-young/bu2016/S2016/cs440/cs540p2_guh_ten-young/test-kec.cpp:557:38:   required from here
/home/ten-young/bu2016/S2016/cs440/cs540p2_guh_ten-young/test-kec.cpp:142:14: error: variable ‘p1_it’ set but not used [-Werror=unused-but-set-variable]
         auto p1_it = map.insert(std::make_pair(p1, 1));